# Generated by Django 5.2.7 on 2026-02-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('weight', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('procedure_of_interest', models.CharField(max_length=150)),
                ('weight_to_lose', models.PositiveIntegerField(blank=True, null=True)),
                ('prev_surgeries', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('travel', models.BooleanField(default=True)),
                ('forms_of_contact', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
