# Generated by Django 5.2.7 on 2026-02-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='height_unit',
            field=models.CharField(default='cm', max_length=3),
        ),
        migrations.AddField(
            model_name='appointment',
            name='weight_to_lose_unit',
            field=models.CharField(default='kg', max_length=3),
        ),
        migrations.AddField(
            model_name='appointment',
            name='weight_unit',
            field=models.CharField(default='kg', max_length=3),
        ),
    ]
