# Generated by Django 5.2.7 on 2026-02-24 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_appointment_height_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='medical_conditions',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='prev_surgeries',
        ),
    ]
