# Generated by Django 5.2.7 on 2026-03-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_appointment_medical_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='was_contacted',
            field=models.BooleanField(default=False),
        ),
    ]
