# Generated by Django 5.2.7 on 2026-04-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_appointment_was_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='was_contacted',
            field=models.BooleanField(default=False),
        ),
    ]
